### ISSUE TITLE
Erro Readme

### ISSUE THREAD

**Issue by gabrielbdornas** [srabuini/feriados#3]
Encontrei um errinho no readme que dificulta a usabilidade do método "DayOfMonth". No arquivo ele está escrito com "o" maiúsculo. Sugiro a correção para:

calendar.add Feriados::Rules::DayOfMonth.new(1, 1, 'New Year')

Tentei abrir um pull request com a correção mas não foi possível (acredito que é um projeto privado)

Grande abraço e Parabéns pela Gem, ela me ajudou e muito!!!

**Comment by srabuini** [comment]
Hey @gabrielbdornas,

Thanks for your suggestion, I've fixed the error and also made some changes.
